== Angular 8 + Spring Boot 2.2 Demo Steps

The brackets at the end of each step indicate the alias's or IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

=== Spring Boot API

. start.spring.io: JPA, H2, Rest Repositories, Lombok, Okta, and Web [`boot-start`]

  http https://start.spring.io/starter.zip dependencies==h2,data-jpa,data-rest,lombok,okta,web javaVersion==11 bootVersion==2.2.0.M4 -d

. Comment out `okta-spring-boot-starter` dependency in `pom.xml`

. Add `Car`, `CarRepository`, and `ApplicationRunner` bean [`boot-entity-lombok`, `boot-repo`, `boot-data`]

. Start and see list of cars in console: `./mvnw spring-boot:run`

. Create `CoolCarController` with a `/cool-cars` endpoint [`boot-cool`]

. Restart and confirm http://localhost:8080/cars works in browser and with https://httpie.org/[HTTPie]

  http POST :8080/cars name='VW Bus'
  http PUT :8080/cars/10 name='Hefe the Bus'
  http DELETE :8080/cars/10

=== Angular App

. Install Angular CLI

  npm i -g @angular/cli@8.0.3

. Run `ng new client --routing --style css --enable-ivy`; show app with `ng serve -o`

. Install Angular Material [`ng add @angular/material`]

. Generate a car service to talk to the API [`a-httpclient-get`]

  ng g s shared/car/car

. Add `HttpClientModule` as an import in `app.module.ts`

. Generate a `CarListComponent` and modify it to use `CarService`

  ng g c car-list

. Update `car-list.component.html` to show the list of cars [`a-ngFor`]

. Update `app.component.html` to use the `<app-car-list>` component

. Start the app, show error, modify `/cool-cars` and repository to use `@CrossOrigin`

=== Angular Material + Giphy

. Add Angular Material imports and modify HTML [`mat-imports`, `mat-toolbar`, `mat-card`]
. Add Animated Cars with Giphy [`ng-giphy-service`, `ng-giphy-foreach`]

=== Add an Edit Feature

. Create a `CarEditComponent` to modify car data

  ng g c car-edit

. Add a link to edit component (+add button) in `car-list.component.html` [`mat-edit`, `mat-add`]

. Import the `FormsModule` in `app.module.ts`

. Add routing to list and edit components in `app-routing.module.ts` [`ng-routes`]

. Modify edit component and car service to add methods for saving and deleting. [`ng-service-api`, `ng-service-cud`, `ng-edit`]

. Make the edit template look good + add some CSS. [`mat-form`]

. Remove `<app-car-list/>` from `app.component.html`, show CORS error and fix [`cors-filter`]

. Restart, demo, and be proud!

=== Authentication with OIDC and Okta

. Uncomment Okta Spring Boot starter in `pom.xml`

. Create OIDC app in Okta; add properties to `application.yml` [`ss-okta`]

. Create `SecurityConfiguration` for resource server [`ss-resource-config`]

. Show 401 at `http://localhost:8080/`

. Commit all changes to Git

. Add Okta's Angular SDK using OktaDev Schematics

  ng add @oktadev/schematics

. Show changes made to project and explain

. **Remove default route** and add `canActivate: [OktaAuthGuard]` to routes in `app-routing.module.ts`

. Modify `app.component.html` to have login and logout buttons + adjust CSS [`mat-login`, `toolbar-spacer`]

. Update `HomeComponent` to use Angular Material and link to Car List [`mat-home`]

. Add `MatButtonModule` and `MatCardModule` to `auth-routing.module.ts`

. Change `<mat-card>` to fill the screen by adding the following to `styles.css`

  mat-card {
    height: 100vh;
  }

. Disable Ivy in `tsconfig.app.json` because https://github.com/angular/angular/issues/29564[Ivy doesn't have CommonJS/UMD support]

. Show app and rejoice 🎉

Source: https://developer.okta.com/blog/2019/05/13/angular-8-spring-boot-2
